app:
  replicas: 1
  env: dev
  container:
    image: nginx:latest
  computerc:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi

hpa:
  enabled: false
  

      