app:
  replicas: 2
  env: qa
  container:
    image: nginx:latest
  computerc:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 200Mi

hpa:
  enabled: false
  

      