{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoScaler
metadata:
  annotations:
    {{- include "nginx-ui.labels" . | nindent 4 }}
spec:
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas:  {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: nginx-ui
  targetCPUUtilizationPercentage: {{ .Values.hpa.cpuuti }}
{{- end -}}