apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
  {{- include "nginx-ui.labels" . | nindent 4}}
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: nginx-ui
  type: NodePort
